version: "3.3"
services:
  frontend:
    image: dashboard-frontend
    build: ./dashboard-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://127.0.0.1:3001
  api:
    image: dashboard-api
    build: ./dashboard-api
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
      - "rabbitmq"
    environment:
      - RABBIT_STRING=amqp://rabbitmq
      - MONGOOSE_STRING=mongodb://mongo/ccdc
      - ALLOWED_CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - SLACK_WEBHOOK=URL
      - SESSION_SECRET=USESOMETHINGSTRONGHEREORTHISWILLBEINSECURE
  mongo:
    image: mongo
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
