version: "3.3"
services:
  frontend:
    image: dashboard-frontend
    build: ./dashboard-frontend
    ports:
      - "3000:80"
    env_file:
      - ./dashboard-frontend/.env  
  api:
    image: dashboard-api
    build: ./dashboard-api
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
      - "rabbitmq"
    env_file:
    - ./dashboard-api/.env
  mongo:
    image: mongoasd
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
